### ISSUE TITLE
Need to run on redmine 2.5.2 (it's the version raspbian brings)

### ISSUE THREAD

**Issue by mwalimu82** [alexandermeindl/redmine_tweaks#22]
Hi,

on my raspberry pi I only managed to install redmine 2.5.2 (it's the version raspbian brings). Is there any older version of redmine_tweaks that might run on my system?

Best regards

Marko

**Comment by alexandermeindl** [comment]
Redmine Tweaks version 0.5.4 is compatible with Redmine version 2.4.6 or higher. Please use the Git tag to get this version.

Best regards
alex
