### ISSUE TITLE
redmine 3.2.0 datepicker, invalid date

### ISSUE THREAD

**Issue by karoroka** [alexandermeindl/redmine_tweaks#23]
Upgrade to 3.2.0 result in error of datepicker (placed at bootom page) and date validation (always invalid date if entered or selected any date)

**Comment by alexandermeindl** [comment]
I fixed this problem. Maybe I've to do some more updates for Redmine 3.2.0 compatibility before I set the git tag 0.5.6 for the stable release.

Let me know, if this didn't fix your problem.

**Comment by karoroka** [comment]
THX, works fine
