### ISSUE TITLE
typo in macros and cheatsheet

### ISSUE THREAD

**Issue by micwill** [alexandermeindl/redmine_tweaks#25]
hallo,

i noticed a typo in the macros list. instead of 
```
last_updated_at
      Displays a date that updated the page.
        {{lastupdated_at}}
        {{lastupdated_at(project_name, wiki_page)}}
        {{lastupdated_at(project_identifier, wiki_page)}}
```

it should read
```
last_updated_at
      Displays a date that updated the page.
        {{last_updated_at}}
        {{last_updated_at(project_name, wiki_page)}}
        {{last_updated_at(project_identifier, wiki_page)}}
```

the respective typo also appears in your cheatsheet although its listed under *Redmine Wiki Extensions Plugin*: https://alphanodes.com/de/redmine-makros-cheat-sheet

i found an additional typo in the cheatsheet:
```
lastupdated_by  {{lastupdated_by}}
```
instead of
```
last_updated_by  {{last_updated_by}}
```

other than that: great plugin! keep up the good work!

**Comment by alexandermeindl** [comment]
Hi micwill,

thanks for reporting! The typo has been fixed in Redmine Tweaks. And yesterday we uploaded a new cheat sheet with the correct macro codes.
