### ISSUE TITLE
Macro user# seems doesn't work

### ISSUE THREAD

**Issue by JL2014** [alexandermeindl/redmine_tweaks#27]
Hi,

I use macro user in my wiki pages, for example :
```
[Report from user#6]
```
But the display is:
```
[Report from user#6]
```
And shoud be 
```
[Report from John Doe]
```
or
```
[Report from John D.]
```
depending on option "Users display format" in Display/Settings of Redmine.

The syntax is it correct ?

Could you add a true macro such as : {{user(6)}} ?

NB: I use CKeditor plugin that changes all behaviors of redmine textareas (wiki and others).

Greetings, JL.

**Comment by alexandermeindl** [comment]
user#1 (with id) or user:admin (with user name) should work, if the user exists. If the user doesn't exist, you'll see just user#1.

Which version of redmine tweaks do you use? This macro is available with version 0.5.6 or newer.

**Comment by JL2014** [comment]
Hi,
I use recent redmine : 3.2.0.devel.15067
The user exists, I check it with the URL : http://redmine_server/users/6/
Greetings.

**Comment by alexandermeindl** [comment]
This should work with the latest Redmine version. But please check the RedmineTweaks version (see my last comment)

**Comment by JL2014** [comment]
I use the lasy git version : 0.5.7

**Comment by alexandermeindl** [comment]
Hmm, strange. I cannot reproduce the problem.

**Comment by JL2014** [comment]
Yes very strange that works fine on **other ** project wiki page...

**Comment by alexandermeindl** [comment]
Do you have installed other plugins? If another plugin overwrites the redmine method "parse_redmine_links", this could be the problem.

**Comment by JL2014** [comment]
Yes I have a lot of plugins...

**Comment by JL2014** [comment]
The problem is conflit with CKEditor ...

**Comment by alexandermeindl** [comment]
You convinced me :+1: I replaced the old syntax with standard {{MACRO}} format. I also included avatar support for the user macro.
Let me know, if there are problems with it.

**Comment by JL2014** [comment]
It's ok for me, sorry for my late response.
