### ISSUE TITLE
Menu item permissions

### ISSUE THREAD

**Issue by pkestefran** [alexandermeindl/redmine_tweaks#29]
Menu items are not visible for Anonymous and Non member groups. 
Not even when all roles are selected and webserver restarted.
Manager and any other member roles are working just fine.

**Comment by alexandermeindl** [comment]
Thanks for reporting! I fixed it with the last commit. Let me know, if you find a problem with it yet.

**Comment by pkestefran** [comment]
hi, thanks for quick fix. Now it works fine :)
