### ISSUE TITLE
Use internal derefer

### ISSUE THREAD

**Issue by CodeInsider** [alexandermeindl/redmine_tweaks#4]
Hi there,

it would be better to use an internal derefer instead of dontknowme.
It won't make much sense to deref a  internal url by giving the call to an external derefer.

You can use a simple route /derefe/:url/ to point to a simple html view which gets the :url parameter in the meta refresh. This way each user could handle it on it's own and style the derefer as expected.

**Comment by alexandermeindl** [comment]
I switch from old days deferer services to html7 noreferrer usage. see f9687b919
